Revert "Truncate database once before specs"
Fixes compile error:

```
In spec/setup/database.cr:8:22

 8 | BaseModel.database.truncate(restart_identity: false)
                        ^-------
Error: no parameter named 'restart_identity'
```

This reverts commit 7bb382fa077ffd14219a2cb9d3f1a7ec8c0d0918.