Fix compile error
```
Error: undefined method 'email_confirmation' for UpdateCurrentUser
```

Missed this in commit df66ca64d11ef09a0d64eaab2f63300405918c40.