Fix compile error
```
Error: undefined constant Shield::OauthAccessTokenCredentials
```

Missed this file in commit fce6f4e53e2155f19238895490b5ed5114a75cf5.

See <https://github.com/GrottoPress/shield/runs/7983212949>.