Fix compile error
```
Error: undefined local variable or method 'current_user_or_bearer'
for Api::LoginsEverywhere::Index
```

Missed these in commit 4742f01e45a591dcaeef76c5101dc3a823eb6703.