Remove `Shield::Hash#initialize`
Subtypes are now required to define their own constructors.

Avoids such compile errors as below, when a subtype add a new
`#initialize` overload:

```
Error: this 'initialize' doesn't explicitly initialize instance
variable '@cost' of BcryptHash, rendering it nilable
```